{{ if .Values.buckets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-buckets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      {{- if .Values.buckets.encrypt }}
      initContainers:
      - name: minio-kes-client
        image: quay.io/minio/kes:2024-03-13T17-52-13Z
        command:
        - /bin/sh
        - -c
        - |
          set -e # make sure the job fails if any instruction fails

          export KES_CLIENT_KEY=/kes-client/private.key
          export KES_CLIENT_CERT=/kes-client/public.crt
          export KES_SERVER=https://{{ .Values.tenant.tenant.name }}-kes-hl-svc.{{ .Release.Namespace }}.svc.cluster.local:7373

          declare -a keys=({{ range .Values.buckets.encrypt }} {{ .key | quote }} {{ end }})
          for key in ${keys[@]}
          do
            if ! ./kes key info $key 2> /dev/null
            then
              ./kes key create $key
              echo "$key created"
            fi
          done
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          name: ca-bundle
          readOnly: true
        - mountPath: /kes-client
          name: client-tls
          readOnly: true
      {{- end }}
      containers:
      - name: minio-client
        image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
        command:
        - /bin/sh
        - -c
        - |
          set -e # make sure the job fails if any instruction fails

          source /tmp/config.env
          mc alias set minio https://minio.{{ .Release.Namespace }}.svc.cluster.local $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD

          {{- if .Values.buckets.default }}
          # Configure default buckets
          mc mb -p {{ range .Values.buckets.default }} minio/{{ .name }} {{ end }}
          {{- end }}

          {{- if .Values.buckets.encrypt }}
          # Configure encrypted buckets
          mc mb -p {{ range .Values.buckets.encrypt }} minio/{{ .name }} {{ end }}
          declare -a names=({{ range .Values.buckets.encrypt }} {{ .name | quote }} {{ end }})
          declare -a keys=({{ range .Values.buckets.encrypt }} {{ .key | quote }} {{ end }})
          for i in ${!names[@]}
          do
            mc encrypt set sse-kms ${keys[i]} minio/${names[i]}
          done
          {{- end }}
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /tmp/config.env
          subPath: config.env
          name: configuration
          readOnly: true
        - mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          name: ca-bundle
          readOnly: true
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: ca-bundle
        configMap:
          defaultMode: 0444
          name: ca-bundle
      - name: client-tls
        secret:
          defaultMode: 0440
          secretName: {{ .Values.tenant.tenant.name }}-client-tls
      - name: configuration
        secret:
          defaultMode: 0440
          secretName: {{ .Values.tenant.secrets.existingSecret.name | default .Values.tenant.secrets.name }}
  backoffLimit: 5
{{ end }}
